/**
 * Trimmed slices of real Sofascore payloads for event 14023963 (Crystal Palace
 * 1-2 Arsenal, 24 May 2026), captured 2026-08-17. Player lists and shot lists
 * are cut down; every field name and value is untouched, so a change in the
 * provider's shape shows up as a test failure rather than as a silent null.
 */

export const SOFASCORE_EVENTS_PAGE: unknown = {
  events: [
    {
      season: {
        name: 'Premier League 25/26',
        year: '25/26',
        editor: false,
        id: 76986,
      },
      roundInfo: {
        round: 36,
      },
      customId: 'Tskb',
      status: {
        code: 100,
        description: 'Ended',
        type: 'finished',
      },
      winnerCode: 2,
      homeTeam: {
        name: 'Fulham',
        slug: 'fulham',
        shortName: 'Fulham',
        nameCode: 'FUL',
        type: 0,
        id: 43,
      },
      awayTeam: {
        name: 'Bournemouth',
        slug: 'bournemouth',
        shortName: 'Bournemouth',
        nameCode: 'BOU',
        type: 0,
        id: 60,
      },
      homeScore: {
        current: 0,
        display: 0,
        period1: 0,
        period2: 0,
        normaltime: 0,
      },
      awayScore: {
        current: 1,
        display: 1,
        period1: 0,
        period2: 1,
        normaltime: 1,
      },
      time: {
        injuryTime1: 4,
        injuryTime2: 5,
        currentPeriodStartTimestamp: 1778339322,
      },
      hasGlobalHighlights: true,
      hasXg: true,
      hasEventPlayerStatistics: true,
      hasEventPlayerHeatMap: true,
      detailId: 1,
      crowdsourcingDataDisplayEnabled: false,
      correctAiInsight: true,
      correctHalftimeAiInsight: false,
      id: 14023948,
      homeRedCards: 1,
      awayRedCards: 1,
      slug: 'bournemouth-fulham',
      startTimestamp: 1778335200,
      finalResultOnly: false,
      feedLocked: true,
      isEditor: false,
    },
    {
      season: {
        name: 'Premier League 25/26',
        year: '25/26',
        editor: false,
        id: 76986,
      },
      roundInfo: {
        round: 36,
      },
      customId: 'dsF',
      status: {
        code: 100,
        description: 'Ended',
        type: 'finished',
      },
      winnerCode: 1,
      homeTeam: {
        name: 'Brighton & Hove Albion',
        slug: 'brighton-and-hove-albion',
        shortName: 'Brighton',
        nameCode: 'BHA',
        type: 0,
        id: 30,
      },
      awayTeam: {
        name: 'Wolverhampton',
        slug: 'wolverhampton',
        shortName: 'Wolves',
        nameCode: 'WOL',
        type: 0,
        id: 3,
      },
      homeScore: {
        current: 3,
        display: 3,
        period1: 2,
        period2: 1,
        normaltime: 3,
      },
      awayScore: {
        current: 0,
        display: 0,
        period1: 0,
        period2: 0,
        normaltime: 0,
      },
      time: {
        injuryTime1: 1,
        injuryTime2: 7,
        currentPeriodStartTimestamp: 1778338900,
      },
      hasGlobalHighlights: true,
      hasXg: true,
      hasEventPlayerStatistics: true,
      hasEventPlayerHeatMap: true,
      detailId: 1,
      crowdsourcingDataDisplayEnabled: false,
      correctAiInsight: true,
      correctHalftimeAiInsight: true,
      id: 14023935,
      slug: 'brighton-and-hove-albion-wolverhampton',
      startTimestamp: 1778335200,
      finalResultOnly: false,
      feedLocked: true,
      isEditor: false,
    },
  ],
  hasNextPage: true,
};

export const SOFASCORE_EVENT_SUMMARY: unknown = {
  event: {
    season: {
      name: 'Premier League 25/26',
      year: '25/26',
      editor: false,
      id: 76986,
    },
    roundInfo: {
      round: 38,
    },
    customId: 'hsR',
    status: {
      code: 100,
      description: 'Ended',
      type: 'finished',
    },
    winnerCode: 2,
    attendance: 25192,
    homeTeam: {
      name: 'Crystal Palace',
      slug: 'crystal-palace',
      shortName: 'Crystal Palace',
      nameCode: 'CRY',
      type: 0,
      id: 7,
      timeActive: [],
    },
    awayTeam: {
      name: 'Arsenal',
      slug: 'arsenal',
      shortName: 'Arsenal',
      nameCode: 'ARS',
      type: 0,
      id: 42,
      timeActive: [],
    },
    homeScore: {
      current: 1,
      display: 1,
      period1: 0,
      period2: 1,
      normaltime: 1,
    },
    awayScore: {
      current: 2,
      display: 2,
      period1: 1,
      period2: 1,
      normaltime: 2,
    },
    time: {
      injuryTime1: 3,
      injuryTime2: 7,
      currentPeriodStartTimestamp: 1779638813,
    },
    hasGlobalHighlights: true,
    hasXg: true,
    hasEventPlayerStatistics: true,
    hasEventPlayerHeatMap: true,
    detailId: 1,
    crowdsourcingDataDisplayEnabled: false,
    correctAiInsight: true,
    correctHalftimeAiInsight: true,
    id: 14023963,
    defaultPeriodCount: 2,
    defaultPeriodLength: 45,
    defaultOvertimeLength: 15,
    slug: 'arsenal-crystal-palace',
    currentPeriodStartTimestamp: 1779638813,
    startTimestamp: 1779634800,
    finalResultOnly: false,
    feedLocked: true,
    seasonStatisticsType: 'overall',
    showTotoPromo: true,
    isEditor: false,
  },
};

export const SOFASCORE_LINEUPS: unknown = {
  confirmed: true,
  home: {
    formation: '3-4-2-1',
    players: [
      {
        player: {
          name: 'Dean Henderson',
          firstName: 'Dean',
          lastName: 'Henderson',
          slug: 'dean-henderson',
          shortName: 'D. Henderson',
          position: 'G',
          jerseyNumber: '1',
          height: 188,
          id: 788134,
        },
        teamId: 7,
        shirtNumber: 1,
        jerseyNumber: '1',
        position: 'G',
        substitute: false,
        captain: true,
        statistics: {
          totalPass: 23,
          accuratePass: 7,
          totalLongBalls: 20,
          accurateLongBalls: 4,
          goalAssist: 0,
          accurateOwnHalfPasses: 3,
          totalOwnHalfPasses: 4,
          accurateOppositionHalfPasses: 4,
          totalOppositionHalfPasses: 19,
          ballRecovery: 11,
          savedShotsFromInsideTheBox: 4,
          saves: 5,
          minutesPlayed: 90,
          touches: 36,
          rating: 7.4,
          possessionLostCtrl: 16,
          expectedAssists: 0.00109601,
          totalBallCarriesDistance: 40.954808874011,
          ballCarriesCount: 8,
          totalProgression: 25.552450792072,
          progressiveBallCarriesCount: 0,
          keeperSaveValue: 0.9285,
          totalShots: 0,
          goalsPrevented: -0.2894,
          passValueNormalized: 0.03,
          dribbleValueNormalized: 0.01,
          defensiveValueNormalized: -0.06,
          goalkeeperValueNormalized: 0.4,
        },
      },
      {
        player: {
          name: 'Will Hughes',
          firstName: 'Will',
          lastName: 'Hughes',
          slug: 'will-hughes',
          shortName: 'W. Hughes',
          position: 'M',
          jerseyNumber: '19',
          height: 185,
          id: 193554,
        },
        teamId: 7,
        shirtNumber: 19,
        jerseyNumber: '19',
        position: 'M',
        substitute: false,
        statistics: {
          totalPass: 31,
          accuratePass: 26,
          totalLongBalls: 2,
          accurateLongBalls: 1,
          goalAssist: 0,
          accurateOwnHalfPasses: 8,
          totalOwnHalfPasses: 9,
          accurateOppositionHalfPasses: 18,
          totalOppositionHalfPasses: 22,
          totalCross: 4,
          aerialLost: 1,
          duelLost: 4,
          duelWon: 5,
          challengeLost: 2,
          totalContest: 1,
          wonContest: 1,
          totalClearance: 1,
          outfielderBlock: 1,
          ballRecovery: 1,
          totalTackle: 2,
          wonTackle: 1,
          wasFouled: 2,
          fouls: 1,
          minutesPlayed: 90,
          touches: 43,
          rating: 7.1,
          possessionLostCtrl: 9,
          expectedAssists: 0.0169919,
          topSpeed: 30.77,
          kilometersCovered: 10.43,
          numberOfSprints: 2,
          totalBallCarriesDistance: 117.96699729717,
          ballCarriesCount: 15,
          totalProgression: 74.804950406813,
          bestBallCarryProgression: 19.536236809538,
          totalProgressiveBallCarriesDistance: 31.255124345878,
          progressiveBallCarriesCount: 2,
          keyPass: 1,
          totalShots: 0,
          passValueNormalized: 0.25,
          dribbleValueNormalized: 0.16,
          defensiveValueNormalized: -0.01,
          metersCoveredRunningKm: 1.61,
          metersCoveredHighSpeedRunningKm: 0.34,
          metersCoveredSprintingKm: 0.06,
        },
      },
      {
        player: {
          name: 'Walter Benítez',
          slug: 'walter-benitez',
          shortName: 'W. Benítez',
          position: 'G',
          jerseyNumber: '44',
          height: 193,
          id: 249859,
        },
        teamId: 7,
        shirtNumber: 44,
        jerseyNumber: '44',
        position: 'G',
        substitute: true,
        statistics: {
          totalShots: 0,
        },
      },
    ],
  },
  away: {
    formation: '4-2-3-1',
    players: [
      {
        player: {
          name: 'Martín Zubimendi',
          slug: 'martin-zubimendi',
          shortName: 'M. Zubimendi',
          position: 'M',
          jerseyNumber: '36',
          height: 180,
          id: 966837,
        },
        teamId: 42,
        shirtNumber: 36,
        jerseyNumber: '36',
        position: 'D',
        substitute: false,
        statistics: {
          totalPass: 67,
          accuratePass: 55,
          totalLongBalls: 5,
          accurateLongBalls: 2,
          goalAssist: 0,
          accurateOwnHalfPasses: 19,
          totalOwnHalfPasses: 19,
          accurateOppositionHalfPasses: 36,
          totalOppositionHalfPasses: 48,
          totalCross: 1,
          accurateCross: 1,
          duelLost: 1,
          duelWon: 2,
          totalClearance: 3,
          ballRecovery: 3,
          totalTackle: 1,
          wasFouled: 1,
          fouls: 1,
          minutesPlayed: 90,
          touches: 84,
          rating: 6.7,
          possessionLostCtrl: 15,
          expectedAssists: 0.039023,
          topSpeed: 28.92,
          kilometersCovered: 9.73,
          numberOfSprints: 2,
          totalBallCarriesDistance: 129.86645530538,
          ballCarriesCount: 14,
          totalProgression: 76.965175299254,
          bestBallCarryProgression: 19.516349941946,
          totalProgressiveBallCarriesDistance: 20.559602355104,
          progressiveBallCarriesCount: 1,
          keyPass: 1,
          totalShots: 0,
          passValueNormalized: 0.17,
          dribbleValueNormalized: 0.11,
          defensiveValueNormalized: -0.14,
          metersCoveredRunningKm: 1.65,
          metersCoveredHighSpeedRunningKm: 0.33,
          metersCoveredSprintingKm: 0.05,
        },
      },
      {
        player: {
          name: 'Noni Madueke',
          slug: 'noni-madueke',
          shortName: 'N. Madueke',
          position: 'F',
          jerseyNumber: '20',
          height: 182,
          id: 966547,
        },
        teamId: 42,
        shirtNumber: 20,
        jerseyNumber: '20',
        position: 'M',
        substitute: false,
        statistics: {
          totalPass: 36,
          accuratePass: 30,
          totalLongBalls: 1,
          accurateLongBalls: 1,
          goalAssist: 0,
          accurateOwnHalfPasses: 5,
          totalOwnHalfPasses: 6,
          accurateOppositionHalfPasses: 25,
          totalOppositionHalfPasses: 30,
          totalCross: 3,
          accurateCross: 1,
          duelLost: 4,
          duelWon: 3,
          challengeLost: 1,
          dispossessed: 1,
          totalContest: 5,
          wonContest: 3,
          bigChanceCreated: 2,
          onTargetScoringAttempt: 2,
          blockedScoringAttempt: 2,
          goals: 1,
          totalClearance: 1,
          ballRecovery: 3,
          unsuccessfulTouch: 2,
          minutesPlayed: 83,
          touches: 55,
          rating: 7.6,
          possessionLostCtrl: 13,
          expectedGoals: 0.1719,
          expectedGoalsOnTarget: 0.2275,
          expectedAssists: 0.299344,
          topSpeed: 30.46,
          kilometersCovered: 7.39,
          numberOfSprints: 5,
          totalBallCarriesDistance: 163.18823044952,
          ballCarriesCount: 16,
          totalProgression: 90.512987465847,
          bestBallCarryProgression: 19.751570967095,
          totalProgressiveBallCarriesDistance: 60.688595814794,
          progressiveBallCarriesCount: 4,
          keyPass: 3,
          totalShots: 4,
          shotValueNormalized: 0.5,
          passValueNormalized: -0.41,
          dribbleValueNormalized: 0.44,
          defensiveValueNormalized: -0.02,
          metersCoveredRunningKm: 1.03,
          metersCoveredHighSpeedRunningKm: 0.22,
          metersCoveredSprintingKm: 0.07,
        },
      },
      {
        player: {
          name: 'Tommy Setford',
          firstName: 'Tommy Setford',
          lastName: '',
          slug: 'tommy-setford',
          shortName: 'T. Setford',
          position: 'G',
          jerseyNumber: '35',
          height: 185,
          id: 1150958,
        },
        teamId: 42,
        shirtNumber: 35,
        jerseyNumber: '35',
        position: 'G',
        substitute: true,
        statistics: {
          totalShots: 0,
        },
      },
    ],
  },
};

export const SOFASCORE_SHOTMAP: unknown = {
  shotmap: [
    {
      player: {
        name: 'Noni Madueke',
        slug: 'noni-madueke',
        shortName: 'N. Madueke',
        position: 'F',
        jerseyNumber: '20',
        id: 966547,
      },
      isHome: false,
      shotType: 'goal',
      goalType: 'regular',
      situation: 'corner',
      playerCoordinates: {
        x: 13.2,
        y: 52.2,
        z: 0,
      },
      bodyPart: 'left-foot',
      goalMouthLocation: 'low-left',
      goalMouthCoordinates: {
        x: 0,
        y: 52.4,
        z: 3.2,
      },
      xg: 0.036703616380692,
      xgot: 0.19625841081142,
      goalkeeper: {
        name: 'Dean Henderson',
        firstName: 'Dean',
        lastName: 'Henderson',
        slug: 'dean-henderson',
        shortName: 'D. Henderson',
        position: 'G',
        jerseyNumber: '1',
        id: 788134,
      },
      id: 7376236,
      time: 48,
      timeSeconds: 2826,
      draw: {
        start: {
          x: 52.2,
          y: 13.2,
        },
        end: {
          x: 47.6,
          y: 0,
        },
        goal: {
          x: 47.6,
          y: 96.8,
        },
      },
      incidentType: 'shot',
      reversedPeriodTime: 43,
      reversedPeriodTimeSeconds: 2574,
      periodTimeSeconds: 126,
    },
    {
      player: {
        name: 'Jean-Philippe Mateta',
        firstName: 'Jean Philippe',
        lastName: 'Mateta',
        slug: 'jean-philippe-mateta',
        shortName: 'J. Mateta',
        position: 'F',
        jerseyNumber: '14',
        id: 848276,
      },
      isHome: true,
      shotType: 'goal',
      goalType: 'regular',
      situation: 'assisted',
      playerCoordinates: {
        x: 6.4,
        y: 50,
        z: 0,
      },
      bodyPart: 'head',
      goalMouthLocation: 'high-right',
      goalMouthCoordinates: {
        x: 0,
        y: 47.3,
        z: 21.5,
      },
      xg: 0.38483673334122,
      xgot: 0.71870571374893,
      goalkeeper: {
        name: 'Kepa Arrizabalaga',
        firstName: 'Kepa',
        lastName: 'Arrizabalaga',
        slug: 'kepa-arrizabalaga',
        shortName: 'K. Arrizabalaga',
        position: 'G',
        jerseyNumber: '13',
        id: 232422,
      },
      id: 7376801,
      time: 89,
      timeSeconds: 5281,
      draw: {
        start: {
          x: 50,
          y: 6.4,
        },
        end: {
          x: 52.7,
          y: 0,
        },
        goal: {
          x: 52.7,
          y: 78.5,
        },
      },
      incidentType: 'shot',
      reversedPeriodTime: 2,
      reversedPeriodTimeSeconds: 119,
      periodTimeSeconds: 2581,
    },
    {
      player: {
        name: 'Eberechi Eze',
        firstName: 'Eberechi',
        lastName: 'Eze',
        slug: 'eberechi-eze',
        shortName: 'E. Eze',
        position: 'M',
        jerseyNumber: '10',
        id: 864921,
      },
      isHome: false,
      shotType: 'save',
      situation: 'assisted',
      playerCoordinates: {
        x: 8.8,
        y: 43.6,
        z: 0,
      },
      bodyPart: 'right-foot',
      goalMouthLocation: 'low-left',
      goalMouthCoordinates: {
        x: 0,
        y: 53.2,
        z: 5.7,
      },
      blockCoordinates: {
        x: 1.2,
        y: 48.7,
        z: 0,
      },
      xg: 0.36332747340202,
      xgot: 0.75082266330719,
      goalkeeper: {
        name: 'Dean Henderson',
        firstName: 'Dean',
        lastName: 'Henderson',
        slug: 'dean-henderson',
        shortName: 'D. Henderson',
        position: 'G',
        jerseyNumber: '1',
        id: 788134,
      },
      id: 7376995,
      time: 90,
      addedTime: 8,
      timeSeconds: 5868,
      draw: {
        start: {
          x: 43.6,
          y: 8.8,
        },
        block: {
          x: 48.7,
          y: 1.2,
        },
        end: {
          x: 46.8,
          y: 0,
        },
        goal: {
          x: 46.8,
          y: 94.3,
        },
      },
      incidentType: 'shot',
      reversedPeriodTime: 1,
      reversedPeriodTimeSeconds: 432,
      periodTimeSeconds: 468,
    },
    {
      player: {
        name: 'Gabriel Jesus',
        firstName: 'Gabriel',
        lastName: 'Jesus',
        slug: 'gabriel-jesus',
        shortName: 'G. Jesus',
        position: 'F',
        jerseyNumber: '9',
        id: 794839,
      },
      isHome: false,
      shotType: 'post',
      situation: 'regular',
      playerCoordinates: {
        x: 14.8,
        y: 36.2,
        z: 0,
      },
      bodyPart: 'right-foot',
      goalMouthLocation: 'right',
      goalMouthCoordinates: {
        x: 0,
        y: 44.6,
        z: 5.7,
      },
      xg: 0.10753486305475,
      xgot: 0,
      goalkeeper: {
        name: 'Dean Henderson',
        firstName: 'Dean',
        lastName: 'Henderson',
        slug: 'dean-henderson',
        shortName: 'D. Henderson',
        position: 'G',
        jerseyNumber: '1',
        id: 788134,
      },
      id: 7375696,
      time: 4,
      timeSeconds: 236,
      draw: {
        start: {
          x: 36.2,
          y: 14.8,
        },
        end: {
          x: 55.4,
          y: 0,
        },
        goal: {
          x: 55.4,
          y: 94.3,
        },
      },
      incidentType: 'shot',
      reversedPeriodTime: 42,
      reversedPeriodTimeSeconds: 2464,
      periodTimeSeconds: 236,
    },
    {
      player: {
        name: 'Christian Nørgaard',
        slug: 'christian-nrgaard',
        shortName: 'C. Nørgaard',
        position: 'M',
        jerseyNumber: '16',
        id: 135256,
      },
      isHome: false,
      shotType: 'miss',
      situation: 'assisted',
      playerCoordinates: {
        x: 19.4,
        y: 73,
        z: 0,
      },
      bodyPart: 'right-foot',
      goalMouthLocation: 'left',
      goalMouthCoordinates: {
        x: 0,
        y: 63.9,
        z: 8.3,
      },
      xg: 0.031245194375515,
      xgot: 0,
      goalkeeper: {
        name: 'Dean Henderson',
        firstName: 'Dean',
        lastName: 'Henderson',
        slug: 'dean-henderson',
        shortName: 'D. Henderson',
        position: 'G',
        jerseyNumber: '1',
        id: 788134,
      },
      id: 7375717,
      time: 10,
      timeSeconds: 569,
      draw: {
        start: {
          x: 73,
          y: 19.4,
        },
        end: {
          x: 36.1,
          y: 0,
        },
        goal: {
          x: 36.1,
          y: 91.7,
        },
      },
      incidentType: 'shot',
      reversedPeriodTime: 36,
      reversedPeriodTimeSeconds: 2131,
      periodTimeSeconds: 569,
    },
  ],
};

export const SOFASCORE_AVERAGE_POSITIONS: unknown = {
  home: [
    {
      player: {
        name: 'Dean Henderson',
        firstName: 'Dean',
        lastName: 'Henderson',
        slug: 'dean-henderson',
        shortName: 'D. Henderson',
        position: 'G',
        jerseyNumber: '1',
        id: 788134,
      },
      averageX: 11.302040816327,
      averageY: 50.424489795918,
      pointsCount: 49,
    },
    {
      player: {
        name: 'Tyrick Mitchell',
        firstName: '',
        lastName: '',
        slug: 'tyrick-mitchell',
        shortName: 'T. Mitchell',
        position: 'M',
        jerseyNumber: '3',
        id: 988275,
      },
      averageX: 33.926086956522,
      averageY: 80.286956521739,
      pointsCount: 23,
    },
  ],
  away: [
    {
      player: {
        name: 'Martín Zubimendi',
        slug: 'martin-zubimendi',
        shortName: 'M. Zubimendi',
        position: 'M',
        jerseyNumber: '36',
        id: 966837,
      },
      averageX: 49.607954545455,
      averageY: 13.197727272727,
      pointsCount: 88,
    },
    {
      player: {
        name: 'Noni Madueke',
        slug: 'noni-madueke',
        shortName: 'N. Madueke',
        position: 'F',
        jerseyNumber: '20',
        id: 966547,
      },
      averageX: 70.185,
      averageY: 17.281666666667,
      pointsCount: 60,
    },
  ],
};

export const SOFASCORE_HEATMAP: unknown = {
  heatmap: [
    {
      x: 44,
      y: 55,
    },
    {
      x: 38,
      y: 83,
    },
    {
      x: 41,
      y: 26,
    },
    {
      x: 33,
      y: 96,
    },
    {
      x: 43,
      y: 73,
    },
    {
      x: 66,
      y: 73,
    },
    {
      x: 67,
      y: 73,
    },
    {
      x: 67,
      y: 53,
    },
    {
      x: 96,
      y: 65,
    },
    {
      x: 64,
      y: 59,
    },
    {
      x: 68,
      y: 54,
    },
    {
      x: 61,
      y: 85,
    },
    {
      x: 91,
      y: 56,
    },
    {
      x: 80,
      y: 94,
    },
    {
      x: 74,
      y: 44,
    },
  ],
};
